version: "3.8"
services:
  ror-hello-world:
    container_name: ror-hello-world-dev
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 5000"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: unless-stopped
